server:
  port: 8082
  servlet.context-path: /currency

spring:
  application.name: currency
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/currency_database
    username: currency
    password: currency

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: '*'

service:
  currency:
    transit-currency-code: USD
  currency-client-api:
    url: https://api.currencyapi.com/v3/latest
    apiKey: cur_live_kOg81YiKjCnGVX6qG1BTq7OjnlXGyJiPHIE7ynMj
    base-currency-attr: base_currency
    currencies-attr: currencies
  cache:
    currency-name: currencies
    rate-name: rates

logging.level:
  liquibase: INFO
  org.hibernate.stat: DEBUG
  org.springframework.web: DEBUG
  com.dvelenteienko.services.currency: DEBUG


