server:
  port: 8082
  servlet.context-path: /currency

spring:
  application.name: currency
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/currency_database
    username: currency
    password: currency

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
    enabled: false
#  cache:
#    type: caffeine
#    cache-names: currencies,rates
#    caffeine:
#      spec: maximumSize=100,expireAfterAccess=600s,

management:
  endpoint.health:
    probes.enabled: true
    show-details: always
  endpoints.web:
    base-path: /actuator
    exposure.include: health,info,caches
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true

service:
  currency:
    transit-currency-code: USD
  currency-client-api:
    url: https://api.currencyapi.com/v3/latest
    apiKey: cur_live_kOg81YiKjCnGVX6qG1BTq7OjnlXGyJiPHIE7ynMj
    base-currency-attr: base_currency
    currencies-attr: currencies
#  cache:
#    default.enabled: false
#    caffeine:
#      enabled: true
#      initial-capacity: 200
#      maximum-size: 500
#      expiration-minutes: 10
#    currency-name: currencies
#    rate-name: rates
  scheduler:
    enabled: false
    cron: 0/30 * * ? * *



logging.level:
  liquibase: INFO
  org.hibernate.stat: DEBUG
  org.springframework.web: DEBUG
  com.dvelenteienko.services.currency: DEBUG

springdoc:
  paths-to-match: /api/v1/**
  swagger-ui:
    deep-linking: true
    default-model-rendering: example
    doc-expansion: none
    operations-sorted: alpha
    tags-sorted: alpha
    path: /swagger-ui


