version: '3.8'
services:
  db:
    image: 'postgres:16.0-alpine'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local